name       : flacon
version    : 5.0.0
release    : 9
source     :
    - https://github.com/flacon/flacon/archive/v5.0.0.tar.gz : 183d364fb47afa8b9e55803b77b99c9eba44d7031a28d4062b1a309b2a9f02b2
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Extracts audio tracks from an audio CD image to separate tracks
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(uchardet)
    - libflac
    - wavpack-utils
rundeps    :
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-test-Monkey-s-Audio-and-tta.patch
    %cmake_ninja -DBUILD_TESTS=Yes
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    export CTEST_OUTPUT_ON_FAILURE=1
    %ninja_check
