name       : flacon
version    : 11.1.0
release    : 13
source     :
    - https://github.com/flacon/flacon/archive/refs/tags/v11.1.0.tar.gz : 43c0cc9a4ef0765cd92cc642c7690c3574430db2b962d497178002866ceeb612
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Extracts audio tracks from an audio CD image to separate tracks
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(taglib)
    - pkgconfig(uchardet)
    - libflac
    - wavpack-utils
rundeps    :
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    %cmake_ninja -DBUILD_TESTS=No
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/share/applications/{flacon.desktop,com.github.Flacon.desktop}
#check      : |
#    export CTEST_OUTPUT_ON_FAILURE=1
#    %ninja_check
