name       : flacon
version    : 4.0.0
release    : 7
source     :
    - https://github.com/flacon/flacon/archive/v4.0.0.tar.gz : 3e128d32e6bc0d1bf618a2312953f9a894cce2699d36abe5f9c38ff1b153dc32
license    : LGPL-2.1-only
component  : multimedia.audio
summary    : Extracts audio tracks from an audio CD image to separate tracks
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(uchardet)
rundeps    :
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
