name       : flacon
version    : 2.1.1
release    : 3
source     :
    - https://github.com/flacon/flacon/archive/v2.1.1.tar.gz : 9ece812c0bd68828301d745fbdddaf9ff2d9e572cc205e20d2bbcb093de98a1b
license    : LGPL-2.1
component  : multimedia.audio
summary    : Flacon extracts individual tracks from one big audio file containing
    the entire album of music and saves them as separate audio files
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(QtCore)
    - pkgconfig(uchardet)
rundeps    :
    - faac-utils
    - lame
    - libflac
    - mp3gain
    - opus
    - shntool
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    %cmake -DUSE_QT4=1 \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
