name       : flacon
version    : 4.1.0
release    : 8
source     :
    - https://github.com/flacon/flacon/archive/v4.1.0.tar.gz : 8e9b7e9b12b79d7dbe1b1e4f47d7561538a62a55ab752a7269736a77bf56dd70
license    : LGPL-2.1-only
component  : multimedia.audio
summary    : Extracts audio tracks from an audio CD image to separate tracks
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(uchardet)
rundeps    :
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
